import { existsSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { PHASE_LABEL, STATE_LABEL, gitChip, relativeTime, type ProjectCard } from '@apeiron/shared';
import { writeFileAtomic } from '../fsutil.ts';

export const MAGNET_USER_FILES = ['MAGNET.md', 'me.md', 'work.md'] as const;
export type MagnetUserFile = (typeof MAGNET_USER_FILES)[number];

const STARTERS: Record<MagnetUserFile, string> = {
  'MAGNET.md': `# Magnet

You are Magnet, the user's assistant across all their projects.

- Short answers. Name the project first, then the problem.
- You are read-only. Anything that writes files, starts an agent or pushes is a proposed action
  the user must approve.
`,
  'me.md': `# About me

Write a few lines about yourself: your name, what you study or do, and how you like to work.
Magnet reads this file.
`,
  'work.md': `# Work

List your businesses, clients, websites and GitHub accounts here. Magnet reads this file.
`,
};

export function magnetDir(home: string): string {
  return path.join(home, 'magnet');
}

/** Writes the starter files on first run. Never touches a file that already exists. */
export function ensureMagnetFiles(home: string): void {
  const dir = magnetDir(home);
  mkdirSync(dir, { recursive: true, mode: 0o700 });
  for (const name of MAGNET_USER_FILES) {
    const file = path.join(dir, name);
    if (!existsSync(file)) writeFileAtomic(file, STARTERS[name]);
  }
}

/** One line per project (docs/data-model.md §6). */
export function projectLine(card: ProjectCard, now = Date.now()): string {
  const parts = [
    card.id,
    card.draft ? 'Survey draft (new project, not created yet)' : STATE_LABEL[card.state],
    card.phase ? PHASE_LABEL[card.phase].toLowerCase() : 'phase unknown',
  ];
  if (card.stack.length) parts.push(card.stack.join(', '));
  parts.push(`git: ${gitChip(card.git).label}`);
  if (card.lastWorked) parts.push(`last ${relativeTime(card.lastWorked, now)}`);
  if (card.nextStep) parts.push(`next: ${card.nextStep}`);
  return `- ${parts.join(' · ')}`;
}

export function writeProjectsMd(home: string, cards: ProjectCard[], now = Date.now()): void {
  const body = [
    '# Projects',
    '',
    `Generated by Apeiron on every scan. Do not edit; changes are overwritten.`,
    '',
    ...cards.map((c) => projectLine(c, now)),
    '',
  ].join('\n');
  writeFileAtomic(path.join(magnetDir(home), 'projects.md'), body);
}
